#this is done by route annotations now
#event_index:
#    path:     /
#    defaults: { _controller: "EventBundle:Event:index" }
#    methods:  GET

event_show:
    path:     /{slug}/show
    defaults: { _controller: "EventBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }
    methods:  DELETE

event_attend:
    path:     /{id}/attend.{format}
    defaults: { _controller: "EventBundle:Event:attend", format: html }
    methods:  GET
    requirements:
          format: json

event_unattend:
    path:     /{id}/unattend.{format}
    defaults: { _controller: "EventBundle:Event:unattend", format: html }
    methods:  GET
    requirements:
              format: json