<?php

namespace EventBundle\Repository;
use Doctrine\ORM\EntityRepository;
use EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getUpcomingEvents($max = null)
    {
        $qb = $this->createQueryBuilder('e')
            ->addOrderBy('e.time', 'ASC');

        if($max){
            $qb->setMaxResults($max);
        }
        return $qb
            ->getQuery()
            ->execute();
    }

    /**
     * @return Event[]
     */
    public function getRecentlyUpdatedEvents()
    {
        return $this->createQueryBuilder('e')
            ->andWhere('e.createdAt > :since')
            ->setParameter('since', new \DateTime('24 hours ago'))
            ->getQuery()
            ->execute();
    }
}
