event_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: EventBundle:Default:index }

foo_bar_event_import:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /

event_annotations:
    resource: "@EventBundle/Controller"
    prefix:   /
    type:     annotation